### ISSUE TITLE
Change logic for ads in time for ESA Winter 2023

### ISSUE THREAD

**Issue by Planks** [esamarathon/esa-commercials#12]
The logic for ESA Winter should be as follows

Ads will be run per intermission (to be set up in the schedule by scheduling team)

Then mid rolls should be run as follows:

For _runs with an estimate of 59 minutes_ or longer, a _120 second midroll_ should be played _every 30 minutes_. This should be played with the same logic as vodstreamer, with the advert placement being calculated and evenly distributed throughout the run, rather than on a heartbeat timer.

So for example 
- A run in the 60-89 minute range would have 1x120s ad placed at 50% of estimate
- A run in the 90-119 minute range would have 2x120s ads placed, at 33% and 66% of estimate
- A run in the 120-149 minute range would have 3x120s ads placed at 25%, 50%, 75% of estimate

And so on

On an intermission scene a 60 second ad should be played every 5 minutes at minute 12 and onwards (so 12, 17, 22 minutes and so on)

**Comment by zoton2** [comment]
As a note to myself, it has also been requested that all the relevant values be changed into configuration options for easy changing without needing to dive into the code ("Minimum run length, frequency, duration, and a cool down before estimate" as stated by Planks).
